### ISSUE TITLE
h2o evaluation

### ISSUE THREAD

**Issue by steveblackburn** [dacapobench/dacapobench#142]
Examine h2o and determine whether it is a suitable workload for inclusion in the suite.

https://github.com/h2oai/h2o-3

**Comment by steveblackburn** [comment]
I spoke with Cliff Click about what sort of workload may be a good one to drive H2O.   Cliff is one of the founders of H2O, has a deep interest in performance analysis, and discussed large scale DaCapo benchmarks with us in the past.

One starting point may be the NOAA dataset and application Cliff used in his [Stanford short course](https://www.coursehero.com/file/19920688/2016-04-CME250A-3/) CME250A, or other [tutorials](https://www.youtube.com/watch?v=pbuMHrGY4LY) he's given.  Cliff couldn't find the dataset while we were speaking but it is publicly available and should be findable among the course resources.  While H2O has many data sets, they are mostly toy.   They may therefore be suitable for a _default_ size workload (e.g. ~10-500MB heap), but not for a large/huge size workload (multi-GB).   I don't know where the data set resides, but [this](https://data.noaa.gov/dataset/dataset/global-surface-summary-of-the-day-gsod),  [this](https://www.ncdc.noaa.gov/cdo-web/datasets), [this](https://aws.amazon.com/noaa-big-data/), [this](https://cloud.google.com/noaa-big-data/) or [this](https://cloud.google.com/bigquery/sample-tables) may be good starting points.   Here's a [website](https://snap.stanford.edu/data/) full of all kinds of data sets, but no sign of the NOAA one.

The behavior of the system varies greatly depending on what it is doing, from compute intensive ('think Mandelbrot') to IO-bound (loading large data sets from csv).  Deep learning has a very different footprint to others.   The hog wild ([SGD](https://en.wikipedia.org/wiki/Stochastic_gradient_descent), stochastic gradient descent) kernel is not very interesting as a workload for runtimes, so probably want to avoid that for DaCapo.   [Random forrest](https://en.wikipedia.org/wiki/Random_forest) is more interesting and is deterministic (it takes a seed), so may be well suited to DaCapo.

H2O can be a pain to build; use it out of the box, to start with.   The standard jar is huge, but a custom jar could be a fraction that size, once we know what we need.

**Comment by caoman** [comment]
For AI and gaming, Java is less popular in these domains, and we don't have much production Java workload on these domains either. We hope the adoption of Java will improve at least in the AI domain.

**Comment by steveblackburn** [comment]
Done
