### ISSUE TITLE
lusearch fails for OpenJDK13

### ISSUE THREAD

**Issue by sujay18108** [dacapobench/dacapobench#179]
Hi,
I get the following build failure with jdk13 and it runs fine with all other JDKs.

`[exec]     [javac] Compiling 824 source files to /home/srcshetty/Desktop/TheProjectParGC/Benchmarks/dacapobench/benchmarks/libs/lucene/build/lucene-7.1.0/build/core/classes/java
     [exec]     [javac] /home/srcshetty/Desktop/TheProjectParGC/Benchmarks/dacapobench/benchmarks/libs/lucene/build/lucene-7.1.0/core/src/java/org/apache/lucene/codecs/blocktree/BlockTreeTermsWriter.java:97: error: heading used out of sequence: <H3>, compared to implicit preceding heading: <H1>
     [exec]     [javac]  * <h3>Term Dictionary</h3>
     [exec]     [javac]    ^
     [exec]     [javac] /home/srcshetty/Desktop/TheProjectParGC/Benchmarks/dacapobench/benchmarks/libs/lucene/build/lucene-7.1.0/core/src/java/org/apache/lucene/codecs/lucene70/package-info.java:21: error: unexpected heading used: <H1>, compared to implicit preceding heading: <H1>
     [exec]     [javac]  * <h1>Apache Lucene - Index File Formats</h1>
     [exec]     [javac]    ^
     [exec]     [javac] /home/srcshetty/Desktop/TheProjectParGC/Benchmarks/dacapobench/benchmarks/libs/lucene/build/lucene-7.1.0/core/src/java/org/apache/lucene/index/PointValues.java:40: error: unexpected heading used: <H1>, compared to implicit preceding heading: <H1>
     [exec]     [javac]  * <h1>Basic Point Types</h1>
     [exec]     [javac]    ^
     [exec]     [javac] /home/srcshetty/Desktop/TheProjectParGC/Benchmarks/dacapobench/benchmarks/libs/lucene/build/lucene-7.1.0/core/src/java/org/apache/lucene/index/PointValues.java:67: error: unexpected heading used: <H1>, compared to implicit preceding heading: <H1>
     [exec]     [javac]  * <h1>Geospatial Point Types</h1>
     [exec]     [javac]    ^
     [exec]     [javac] /home/srcshetty/Desktop/TheProjectParGC/Benchmarks/dacapobench/benchmarks/libs/lucene/build/lucene-7.1.0/core/src/java/org/apache/lucene/index/PointValues.java:77: error: unexpected heading used: <H1>, compared to implicit preceding heading: <H1>
     [exec]     [javac]  * <h1>Advanced usage</h1>
     [exec]     [javac]    ^
     [exec]     [javac] /home/srcshetty/Desktop/TheProjectParGC/Benchmarks/dacapobench/benchmarks/libs/lucene/build/lucene-7.1.0/core/src/java/org/apache/lucene/search/Sort.java:37: error: heading used out of sequence: <H3>, compared to implicit preceding heading: <H1>
     [exec]     [javac]  * <h3>Valid Types of Values</h3>
     [exec]     [javac]    ^
     [exec]     [javac] /home/srcshetty/Desktop/TheProjectParGC/Benchmarks/dacapobench/benchmarks/libs/lucene/build/lucene-7.1.0/core/src/java/org/apache/lucene/util/packed/package-info.java:34: error: heading used out of sequence: <H3>, compared to implicit preceding heading: <H1>
     [exec]     [javac]  * <h3>In-memory structures</h3>
     [exec]     [javac]    ^
     [exec]     [javac] Note: Some input files use or override a deprecated API.
     [exec]     [javac] Note: Recompile with -Xlint:deprecation for details.
     [exec]     [javac] 7 errors`

**Comment by steveblackburn** [comment]
This has been fixed.  Closing.
