### ISSUE TITLE
Validation FAILED for tomcat default

### ISSUE THREAD

**Issue by oubidar-Abderrahim** [dacapobench/dacapobench#184]
On macOS Mojave v10.14.6, when running the tomcat benchmark using jdk1.8.0_221 with the following command:

`jdk1.8.0_221.jdk/Contents/Home/bin/java -jar dacapo-9.12-MR1-bach.jar tomcat`

I get the following output: 
`Using scaled threading model. 8 processors detected, 8 threads used to drive the workload, in a possible range of [1,64]
Server thread created
===== DaCapo 9.12-MR1 tomcat starting =====
Loading web application
Creating client threads
Waiting for clients to complete
URL /examples/jsp/jsp2/el/basic-arithmetic.jsp returned status 500 (expected 200)
...
...
URL /examples/jsp/tagplugin/choose.jsp returned status 500 (expected 200)
URL /examples/jsp/tagplugin/choose.jsp returned status 500 (expected 200)
Client threads complete ... unloading web application
Digest validation failed for stderr.log, expecting 0xda39a3ee5e6b4b0d3255bfef95601890afd80709 found 0xab4fcb7050405e9dfe9868ed6d2d75fe0f9ae4eb
===== DaCapo 9.12-MR1 tomcat FAILED =====
Server stopped ... iteration complete
Validation FAILED for tomcat default`

The same output is produced when using OpenJDK 11.0.4 and GraalVM EE Java8 20.0.0

**Comment by steveblackburn** [comment]
Thanks for this.   I am investigating.

**Comment by steveblackburn** [comment]
believe that this is an issue with tomcat / the jvm, so it won't be something we're fixing in the old benchmark release.

However, the new release is very nearly here and it has a completely new tomcat version and works with current jvms.

**Comment by oubidar-Abderrahim** [comment]
Okay, thank you
looking forward to the new release
