### ISSUE TITLE
Issue setting up big data

### ISSUE THREAD

**Issue by atpoverload** [dacapobench/dacapobench#185]
I am currently trying to set up the large data (primarily for graphchi) and I am having trouble validating it. I am using the 309e1fa evaluation jar but it doesn't seem to be able to pull the large data. I also tried to manually pull the large data from the other repo but the jar is unable to validate it. Any idea what I may be doing wrong here?

**Comment by steveblackburn** [comment]
We've completely reworked the packaging, so this problem will no longer exist (big data is no longer separately downloaded; it's part of the zip file distribution).
