### ISSUE TITLE
tomcat failed with "Digest validation failed" for java14

### ISSUE THREAD

**Issue by yfxhust** [dacapobench/dacapobench#187]
I think it is caused by JEP358. JEP358 changes the exception log format.
Hope it can be fixed in near future.

The detail error log is as following:

URL /examples/jsp/error/err.jsp?name=audi&submit=Submit
   expected 4b5b51a41a2720387c089e6f830684578bc40393
   found    49220fc801c00017479a81cbe5575b4ec4213bad
   response code 500, log file result.17.21.25.html
URL /examples/jsp/error/err.jsp?name=audi&submit=Submit
   expected 4b5b51a41a2720387c089e6f830684578bc40393
   found    49220fc801c00017479a81cbe5575b4ec4213bad
   response code 500, log file result.0.21.25.html
URL /examples/jsp/error/err.jsp?name=audi&submit=Submit
   expected 4b5b51a41a2720387c089e6f830684578bc40393
   found    49220fc801c00017479a81cbe5575b4ec4213bad
   response code 500, log file result.20.21.25.html
Client threads complete ... unloading web application
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/media/disk1/xxxxx/scratch/lib/catalina.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Digest validation failed for stderr.log, expecting 0xda39a3ee5e6b4b0d3255bfef95601890afd80709 found 0xee64d003d59958c3650a51b2a4b63617808f2ad3

**Comment by steveblackburn** [comment]
Fixed in upcoming release.
