### ISSUE TITLE
DaCapo Chopin: jython prints unnecessary characters to stdout

### ISSUE THREAD

**Issue by k-sareen** [dacapobench/dacapobench#196]
DaCapo Chopin jython (commit: https://github.com/dacapobench/dacapobench/commit/69a704ef4436196295e8e107f0a5f5f5212c125a) prints some unnecessary characters (`^G`) to stdout. This results in output logs not being able to parse at times.

Example (output of `cat -vet`):
```
[...]
* Round 2 done.$
$
^G===== DaCapo evaluation-git-69a704e jython completed warmup 4 in 104017 msec =====$
===== DaCapo evaluation-git-69a704e jython starting =====$
[...]
```

**Comment by steveblackburn** [comment]
[Fixed](https://github.com/dacapobench/dacapobench/commit/bc1b237c0a5158612fcd2111371829897329f74c)
