### ISSUE TITLE
Failure in Getting Source code 

### ISSUE THREAD

**Issue by maryammsd** [dacapobench/dacapobench#197]
Hello, 

I wanna get the source code of the benchmark. I cloned the repo and tried to execute the "ant " command within benchmark directory. However, I got the following error:

avrora:
     [exec] Buildfile: PATH/dacapobench/benchmarks/source-dir/benchmarks/bms/avrora/build.xml
     [exec] 
     [exec] incremental:
     [exec] 
     [exec] source:
     [exec] 
     [exec] svn-source:
     [exec] 
     [exec] cvs-source:
     [exec] 
     [exec] scm-init:
     [exec] 
     [exec] check-cvs-source:
     [exec] 
     [exec] BUILD FAILED
     [exec] PATH/dacapobench/benchmarks/source-dir/benchmarks/bms/common.xml:46: The following error occurred while executing this line:
     [exec] PATH/dacapobench/benchmarks/source-dir/benchmarks/bms/common.xml:74: The following error occurred while executing this line:
     [exec] PATH/dacapobench/benchmarks/source-dir/benchmarks/util.xml:216: The following error occurred while executing this line:
     [exec] PATH/source/dacapobench/benchmarks/source-dir/benchmarks/util.xml:256: The following error occurred while executing this line:
     [exec] PATH/source/dacapobench/benchmarks/source-dir/benchmarks/util.xml:238: java.io.IOException: Cannot run program "cvs" (in directory "/PATH/dacapobench/benchmarks/source-dir/benchmarks/cvs-20211011-0323"): error=2, No such file or directory
     [exec] 
     [exec] check-cvs-source.checkandupdate:	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
     [exec] 
     [exec] 
     [exec] 	at java.lang.Runtime.exec(Runtime.java:620)check-cvs-source.update:
     [exec] 
     [exec] 
     [exec] 	at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)get-cvs-source:
     [exec] 
     [exec] 	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:424)
     [exec]     [mkdir] Created dir: PATH/source/dacapobench/benchmarks/source-dir/benchmarks/cvs-20211011-0323
     [exec] 	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:438)     [echo] Date is: 20131011
     [exec] 
     [exec] 	at org.apache.tools.ant.taskdefs.AbstractCvsTask.runCommand(AbstractCvsTask.java:352)
     [exec] 	at org.apache.tools.ant.taskdefs.AbstractCvsTask$$Lambda$74.0000000000000000.accept(Unknown Source)
     [exec] 	at java.util.Vector.forEach(Vector.java:1275)
     [exec] 	at org.apache.tools.ant.taskdefs.AbstractCvsTask.execute(AbstractCvsTask.java:406)
     [exec] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
     [exec] 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
     [exec] 	at org.apache.tools.ant.Task.perform(Task.java:350)
     [exec] 	at org.apache.tools.ant.Target.execute(Target.java:449)
     [exec] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
     [exec] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
     [exec] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
     [exec] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
     [exec] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
     [exec] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
     [exec] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
     [exec] 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
     [exec] 	at org.apache.tools.ant.Task.perform(Task.java:350)
     [exec] 	at org.apache.tools.ant.Target.execute(Target.java:449)
     [exec] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
     [exec] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
     [exec] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
     [exec] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
     [exec] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
     [exec] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
     [exec] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
     [exec] 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
     [exec] 	at org.apache.tools.ant.Task.perform(Task.java:350)
     [exec] 	at org.apache.tools.ant.Target.execute(Target.java:449)
     [exec] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
     [exec] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
     [exec] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
     [exec] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
     [exec] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
     [exec] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
     [exec] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
     [exec] 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
     [exec] 	at org.apache.tools.ant.Task.perform(Task.java:350)
     [exec] 	at org.apache.tools.ant.Target.execute(Target.java:449)
     [exec] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
     [exec] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
     [exec] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
     [exec] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
     [exec] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
     [exec] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
     [exec] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
     [exec] 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
     [exec] 	at org.apache.tools.ant.Task.perform(Task.java:350)
     [exec] 	at org.apache.tools.ant.Target.execute(Target.java:449)
     [exec] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
     [exec] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
     [exec] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
     [exec] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
     [exec] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
     [exec] 	at org.apache.tools.ant.Main.runBuild(Main.java:827)
     [exec] 	at org.apache.tools.ant.Main.startAnt(Main.java:223)
     [exec] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
     [exec] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
     [exec] Caused by: java.io.IOException: error=2, No such file or directory
     [exec] 	at java.lang.UNIXProcess.forkAndExec(Native Method)
     [exec] 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
     [exec] 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
     [exec] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
     [exec] 	... 76 more
     [exec] 
     [exec] Total time: 0 seconds
     [exec] Result: 1
     [echo] avrora: FAIL

Can you please help me in solving it?

**Comment by maryammsd** [comment]
Seems there are a lot of inconsistency in this repo due to invalid urls, version of tools, etc in the scripts written to fetch the source code. One must go through the scripts and correct them by himself. It would be good if the maintainers resolve these issues! However, I am doubtful if there is anyone still on this benchmark!!!

**Comment by caizixian** [comment]
The Chopin branch should have various build issues fixed https://github.com/dacapobench/dacapobench/tree/dev-chopin
That's the branch people are actively working on at the moment.
