### ISSUE TITLE
pmd validation failure when other profiler/tool instantiates the system logger

### ISSUE THREAD

**Issue by mur47x111** [dacapobench/dacapobench#199]
pmd's logger dumps the following to stdout:
```
Oct 02, 2021 12:53:13 PM net.sourceforge.pmd.typeresolution.ClassTypeResolver visit
WARNING: Could not find class net.sourceforge.pmd.ant.PMDTask, due to: java.lang.NoClassDefFoundError: org/apache/tools/ant/Task
Oct 02, 2021 12:53:35 PM net.sourceforge.pmd.typeresolution.ClassTypeResolver visit
WARNING: Could not find class net.sourceforge.pmd.cpd.CPDTask, due to: java.lang.NoClassDefFoundError: org/apache/tools/ant/Task
```
But if there is another profiler/tool instantiates the system logger, the above message will be dumped to stderr as well and thus fail the validation.
Adding `org/apache/tools/ant/Task` to pmd's class path would avoid the NoClassDefFoundError and fix the validation issue.

**Comment by steveblackburn** [comment]
I believe this is fixed in the forthcoming RC.  Can you please check, or else provide info on how to reproduce so I can check?
