### ISSUE TITLE
Mavenized version of java projects DaCapo uses

### ISSUE THREAD

**Issue by SaliasO** [dacapobench/dacapobench#200]
Hello, I am searching for Java projects in a "mavenized" format. The projects used by DaCapo for benchmarking sound very interessting. Are they provided in a mavenized form somewhere?
Best regards,
Salih

**Comment by steveblackburn** [comment]
I'm not quite sure what you're asking for.   DaCapo depends on external projects for each of those workloads.  Those projects use various build systems, but we're not in control of their build systems.
