### ISSUE TITLE
tradesoap and tradebeans

### ISSUE THREAD

**Issue by ppoooo0** [dacapobench/dacapobench#216]
Hello,I would like to ask if there is source code for tradesoap and tradebeans.I would be grateful if I could get your reply.

**Comment by steveblackburn** [comment]
If you're interested in the bach release, you can find it in the source zip: 
https://sourceforge.net/projects/dacapobench/files/9.12-bach-MR1/

If you're looking at the master, or upcoming release, you should check out the source and then build daytrader (`ant daytrader`), which will build both tradebeans and tradesoap.  The daytrader sources will be in the lib/daytrader directory.
