### ISSUE TITLE
Getting exact source for downloaded jar

### ISSUE THREAD

**Issue by tstuefe** [dacapobench/dacapobench#222]
Sorry if I miss something obvious.

I try to correlate a DaCapo failure I see with the sources. But I need help figuring out which version exactly I am running.

The benchmark is the downloaded "dacapo-9.12-MR1-bach.jar", which I hope is stable, right? So, "dacapo-9.12-MR1-bach.jar" downloaded today will be the same as tomorrow?

Looking at the sources, we have only a single tag, "9.12-vbump". Is that what "dacapo-9.12-MR1-bach.jar" was built from?

**Comment by steveblackburn** [comment]
I am confused.  Have you download the source distribution?

—Steve
________________________________
From: Thomas Stuefe ***@***.***>
Sent: Thursday, May 25, 2023 4:58:44 PM
To: dacapobench/dacapobench ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dacapobench/dacapobench] Getting exact source for downloaded jar (Issue #222)


Sorry if I miss something obvious.

I try to correlate a DaCapo failure I see with the sources. But I need help figuring out which version exactly I am running.

The benchmark is the downloaded "dacapo-9.12-MR1-bach.jar", which I hope is stable, right? So, "dacapo-9.12-MR1-bach.jar" downloaded today will be the same as tomorrow?

Looking at the sources, we have only a single tag, "9.12-vbump". Is that what "dacapo-9.12-MR1-bach.jar" was built from?

**Comment by steveblackburn** [comment]
The older releases came with source zips.   You should use that.  You'll find it here: https://sourceforge.net/projects/dacapobench/files/9.12-bach-MR1/
