### ISSUE TITLE
tradebeans/tradesoap in 23.11-chopin fails with OpenJDK11 built from source

### ISSUE THREAD

**Issue by David-Raccoon** [dacapobench/dacapobench#241]
Hi, I'm from [Issue#225](https://github.com/dacapobench/dacapobench/issues/225), and the issue with tradebeans/tradesoap still remains with the latest release version.
I've test the new DaCapo-23.11-chopin release version on OpenJDK11u built from source https://github.com/openjdk/jdk11u, as suggested by @caizixian. But the silent shutdown problem still exists.
The JDK build configs:
```
./configure --with-target-bits=64 --with-debug-level=release
```
The Java commmand:
```
java -jar dacapo-23.11-chopin.jar tradebeans
```
```
Using scaled threading model. 40 processors detected, 40 threads used to drive the workload, in a possible range of [1,2048]
Version: daytrader svn-1904225 wildfly 26.1.3.Final (use -p to print nominal benchmark stats)
DayTrader is using port 8080 (8080+0). Configure with -Djboss.http.port and/or -Djboss.socket.binding.port-offset
NOTE: Starting watchdog timer with timeout of 110 seconds. Adjust timeout with the -f command line option.
```
An observation is that is time of the process does not reaches 110 seconds. I guess the shutdown does not result from the time out.

**Comment by caizixian** [comment]
Can you reproduce the issue with any prebuilt OpenJDK, such as Temurin?

**Comment by David-Raccoon** [comment]
I've tested two versions, JDK11 and JDK21. They all work out fine. @caizixian 
```
openjdk version "11.0.21" 2023-10-17
OpenJDK Runtime Environment Temurin-11.0.21+9 (build 11.0.21+9)
OpenJDK 64-Bit Server VM Temurin-11.0.21+9 (build 11.0.21+9, mixed mode)
```
```
openjdk version "21.0.1" 2023-10-17 LTS
OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode, sharing)
```

**Comment by caizixian** [comment]
OK, so it seems to suggest that the JDK you built instead of the benchmark has some problems.

**Comment by caizixian** [comment]
Are you using exploded build? What's the exact `make` command you use when building the JDK?

**Comment by David-Raccoon** [comment]
Simply ```make```, the default build command.

**Comment by caizixian** [comment]
You should run `make images`, and then use `images/jdk/bin/java`

**Comment by David-Raccoon** [comment]
It works fine! Thanks a lot.
