### ISSUE TITLE
--sizes option outputs to stderr

### ISSUE THREAD

**Issue by guilhas07** [dacapobench/dacapobench#265]
I don't know if this is the intended behaviour but when running `java -jar dacapo/dacapo-23.11-chopin.jar --sizes avrora` the output gets printed to stderr instead of stdout which seems wrong/unintuitive. 

## To reproduce:
`java -jar dacapo/dacapo-23.11-chopin.jar --sizes avrora 2>error` doesn't print size info

**Comment by steveblackburn** [comment]
Thanks.  Fixed.
