### ISSUE TITLE
Server side pre-request hook in tomcat does not work

### ISSUE THREAD

**Issue by tianleq** [dacapobench/dacapobench#297]
https://github.com/dacapobench/dacapobench/blob/d8b6138eb58e45b0ec28c238dd436e2203d756ba/benchmarks/bms/tomcat/tomcat.patch#L117

The check `t == null` will prevent the hook being executed. This check is simply wrong and does not make sense.

**Comment by steveblackburn** [comment]
Fixed in 72cedc96bd38d73c3a1c2e0cd4fe2beb2a413003
